### ISSUE TITLE
[select] multiple css shadow parts with same name of `label` causing incorrect styling

### ISSUE THREAD

**Issue by sriramasdanturthi** [tyler-technologies-oss/forge#891]
**Describe the bug:**
Forge Select has two Label parts in shadow dom with same part name which is causing issues with styling the parts. If you could remove the part(label) inside forge-select and use forge-field part(label) to display label which will avoid lot of styling issues.

I am trying to change required indicator for the forge fields ex: text-field, select
sample css

```css
.success:nth-child(1)::part(label)::before {
	color: green;
	content: '\2714'
}
```

if i apply the style to forge select i saw two check marks.
